use Mix.Config

config :isketo,
  keto_banned_ingredients:
    [
      "apples?",
      "bananas?",
      "beers?",
      "beans?",
      "biscuit?",
      "bread",
      "cakes?",
      "cand(y|ies)",
      "cassava",
      "cereals?",
      "chickpeas?",
      "chocolate",
      "chocolate (milk|powder)",
      "ciabattas?",
      "corn",
      "cornstarch",
      "desserts?",
      "ice-?cream",
      "lentils?",
      "melons?",
      "salty snacks",
      "((muscovado|refined) )?sugar",
      "oats?",
      "parsnips?",
      "pasta",
      "peas?",
      "pears?",
      "pizza dough",
      "rice",
      "soy",
      "((sweet|white) )?potatos?",
      "toasts?",
      "vodka",
      "watermelons?",
      "wheat flour",
      "whisky",
      "wine",
      "yam"
    ]
    |> Enum.map(fn s -> ~r/#{s}/iu end)
